CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE,
  "email" varchar UNIQUE,
  "password_hash" varchar,
  "avatar_url" varchar,
  "bio" text,
  "created_at" timestamp
);

CREATE TABLE "anime" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "anilist_id" int UNIQUE,
  "title" varchar,
  "description" text,
  "image_url" varchar,
  "episodes" int,
  "score" decimal,
  "status" varchar,
  "release_year" int
);

CREATE TABLE "genres" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE
);

CREATE TABLE "anime_genres" (
  "anime_id" int,
  "genre_id" int
);

CREATE TABLE "platforms" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "logo_url" varchar,
  "website_url" varchar
);

CREATE TABLE "anime_platforms" (
  "anime_id" int,
  "platform_id" int,
  "country" varchar,
  "streaming_url" varchar
);

CREATE TABLE "watchlists" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "anime_id" int,
  "status" varchar,
  "added_at" timestamp
);

CREATE TABLE "favorites" (
  "user_id" int,
  "anime_id" int
);

CREATE TABLE "reviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "anime_id" int,
  "rating" int,
  "comment" text,
  "created_at" timestamp
);

CREATE TABLE "friends" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id" int,
  "receiver_id" int,
  "status" varchar,
  "created_at" timestamp
);

CREATE TABLE "recommendations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "from_user_id" int,
  "to_user_id" int,
  "anime_id" int,
  "message" text,
  "created_at" timestamp
);

ALTER TABLE "anime_genres" ADD FOREIGN KEY ("anime_id") REFERENCES "anime" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anime_genres" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anime_platforms" ADD FOREIGN KEY ("anime_id") REFERENCES "anime" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anime_platforms" ADD FOREIGN KEY ("platform_id") REFERENCES "platforms" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "watchlists" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "watchlists" ADD FOREIGN KEY ("anime_id") REFERENCES "anime" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favorites" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favorites" ADD FOREIGN KEY ("anime_id") REFERENCES "anime" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reviews" ADD FOREIGN KEY ("anime_id") REFERENCES "anime" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "friends" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "friends" ADD FOREIGN KEY ("receiver_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recommendations" ADD FOREIGN KEY ("from_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recommendations" ADD FOREIGN KEY ("to_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recommendations" ADD FOREIGN KEY ("anime_id") REFERENCES "anime" ("id") DEFERRABLE INITIALLY IMMEDIATE;
